
# Uso de SpEL y Profiles

## Spring Expression Language
El lenguaje de Expresión de Spring es un poderoso lenguaje de expresión ue soporta la búsqueda y manipulación de un objeto como grafo en tiempo de ejecución. El cual, fue creado para ser usado en varios subproyectos de Spring.

No esta directamente atado a Spring, por lo que puede ser usado de forma independiente(es decir, no necesita un `ApplicationContext`. Aunque mayormente, estremos usando el SpEL dentro del contenedor de Spring.

Le lenguaje de expresión soporta la siguiente funcionalidad:

* Expresion de literales
* Operadores relacionales y booleanos
* Expresiones regulares
* Expresiones de clases
* Acceder a propiedades, arreglos, listas y mapas
* Invocación de métodos
* Asignaciones
* Llamadas a constructores
* Referencias a beans
* Construcción de arreglos
* Listas en línea
* Operador ternario
* Variables
* Funciones definidas por el usuario
* Proyección de colecciones
* Selección de colecciones
* Expresiones en plantillas

La interface `ExpressionParser` es responsable del parseo de las expresiones, puede arrojar dos excepciones: `ParseException` y `EvaluationException`; y los paquetes de uso principales para el manejo de SpEL son: `org.springframework.expression` y el subpaquete `spel.support`.

*SpELInterfaceTests.java*

[source,java,linenums]
----
package com.makingdevs.practica13;

import static org.springframework.util.Assert.isTrue;

import java.util.Date;
import java.util.GregorianCalendar;

import org.junit.Test;
import org.springframework.expression.EvaluationContext;
import org.springframework.expression.Expression;
import org.springframework.expression.ExpressionParser;
import org.springframework.expression.spel.standard.SpelExpressionParser;
import org.springframework.expression.spel.support.StandardEvaluationContext;

public class SpELInterfaceTests {

  ExpressionParser parser = new SpelExpressionParser();

  @Test
  public void testStringExpression() {
    Expression exp = parser.parseExpression("'Making Devs'");
    String message = (String) exp.getValue();
    isTrue("Making Devs".equals(message));
  }

  @Test
  public void testMethodInvocation() {
    Expression exp = parser.parseExpression("('We are ' + 'Making Devs').concat('!!!')");
    String message = (String) exp.getValue();
    isTrue("We are Making Devs!!!".equals(message));
  }

  @Test
  public void testTypeInvocation() {
    Expression exp = parser.parseExpression("'Making Devs'.bytes");
    byte[] bytes = (byte[]) exp.getValue();
    isTrue(new String(bytes).equals("Making Devs"));
    exp = parser.parseExpression("'We are making software'.bytes.length");
    int length = (Integer) exp.getValue();
    isTrue("We are making software".getBytes().length == length);
  }

  @Test
  public void testValueByType() {
    ExpressionParser parser = new SpelExpressionParser();
    Expression exp = parser.parseExpression("new String('Software development').toUpperCase()");
    String message = exp.getValue(String.class);
    isTrue("SOFTWARE DEVELOPMENT".equals(message));
  }

  @Test
  public void testGetValueFromADifferentContext() {
    GregorianCalendar calendar = new GregorianCalendar(2013, 6, 12);
    ExpressionParser parser = new SpelExpressionParser();
    Expression exp = parser.parseExpression("time");
    EvaluationContext context = new StandardEvaluationContext(calendar);
    Date date = (Date) exp.getValue(context);
    isTrue(date.equals(calendar.getTime()));
  }

}
----

En el uso independiente de SpEL existe la necesidad de crear un parser, parsear las expresiones y quiza proveer de la evaluación de contextos de evaluación y objeto raíz de contexto. Sin embargo, el uso más común es en archivos de configuración como parte de la asignación de los valores establecidos a los beans.

*UsingLanguageTests.java*

[source,java,linenums]
----
package com.makingdevs.practica13;

import org.junit.Test;
import org.springframework.expression.Expression;
import org.springframework.expression.ExpressionParser;
import org.springframework.expression.spel.standard.SpelExpressionParser;
import org.springframework.util.Assert;
import static org.springframework.util.Assert.*;
import static org.junit.Assert.*;

public class UsingLanguageTests {

  ExpressionParser parser = new SpelExpressionParser();

  @Test
  public void testInvokeStaticMethod() {
    // El prefijo 'T' indica el tipo, en este caso la clase Math
    Expression exp = parser.parseExpression("T(Math).random() * 100.0");
    // En la expresion anterior, el resultado de la llamada a random
    double value = exp.getValue(double.class);
    Assert.notNull(value);
    System.out.println(value);
  }

  @Test
  public void testRelationalOperators() {
    ExpressionParser parser = new SpelExpressionParser();
    isTrue(parser.parseExpression("2==2").getValue(boolean.class));
    isTrue(parser.parseExpression("2<3").getValue(boolean.class));
    isTrue(parser.parseExpression("3>2").getValue(boolean.class));
    isTrue(parser.parseExpression("0!=1").getValue(boolean.class));
  }

  @Test
  public void testLogicalOperators() {
    isTrue(parser.parseExpression("true and true").getValue(boolean.class));
    isTrue(parser.parseExpression("true or true").getValue(boolean.class));
    isTrue(parser.parseExpression("!false").getValue(boolean.class));
    isTrue(parser.parseExpression("not false").getValue(boolean.class));
    isTrue(parser.parseExpression("true and not false").getValue(boolean.class));
  }

  @Test
  public void testMathematicalOperators() {
    ExpressionParser parser = new SpelExpressionParser();
    assertSame(2, parser.parseExpression("1+1").getValue(int.class));
    assertSame(0, parser.parseExpression("1-1").getValue(int.class));
    assertSame(1, parser.parseExpression("1/1").getValue(int.class));
    assertSame(1, parser.parseExpression("1*1").getValue(int.class));
    assertSame(1, parser.parseExpression("1^1").getValue(int.class));
    assertTrue(1D == parser.parseExpression("1e0").getValue(double.class));
    assertEquals("foobar", parser.parseExpression("'foo'+'bar'").getValue(String.class));
  }

  @Test
  public void testTernaryElvisAndSafeNavigationOperators() {
    assertEquals("foo", parser.parseExpression("true ? 'foo' : 'bar'").getValue(String.class));
    assertEquals("es nulo", parser.parseExpression("null?:'es nulo'").getValue(String.class));
    assertEquals(null, parser.parseExpression("null?.foo").getValue(String.class));
  }

}
----

### Uso de SpEL dentro de los archivos de configuración

*SpELInjection.java*

[source,java,linenums]
----
package com.makingdevs.practica14;

public class SystemInfo {
  private String javaHome;
  private String osName;
  private String osVersion;
  private String userDir;
  private String userHome;
  private String userName;
  // getters and setters
}
----

*SpELInjection.xml*

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:util="http://www.springframework.org/schema/util"
  xmlns:context="http://www.springframework.org/schema/context"
  xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-4.0.xsd
    http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.0.xsd">

  <bean id="userWitSpel" class="com.makingdevs.practica14.SystemInfo">
    <property name="javaHome" value="#{systemProperties['java.home']}"/>
    <property name="osName" value="#{systemProperties['os.name']}"/>
    <property name="osVersion" value="#{systemProperties['os.version']}"/>
    <property name="userDir" value="#{systemProperties['user.dir']}"/>
    <property name="userHome" value="#{systemProperties['user.home']}"/>
    <property name="userName" value="#{systemProperties['user.name']}"/>
  </bean>

  <!-- Loading file with properties -->
  <util:properties id="userInfo" location="classpath:/com/makingdevs/practica14/userInfo.properties" />

  <!-- Injecting properties with SpEL -->
  <bean id="userInfoSpel" class="com.makingdevs.model.User">
    <property name="id" value="#{userInfo[id]}"/>
    <property name="username" value="#{userInfo[username]}"/>
    <property name="enabled" value="#{userInfo[enabled]}"/>
  </bean>

  <!-- Placeholders values -->
  <context:property-placeholder location="classpath:/com/makingdevs/practica14/userInfo.properties" />

  <!-- Injecting properties with SpEL -->
  <bean id="userInfoPlaceholders" class="com.makingdevs.model.User">
    <property name="id" value="${id}"/>
    <property name="username" value="${username}"/>
    <property name="enabled" value="${enabled}"/>
  </bean>
</beans>
----

*SpELXmlConfigTests.java*

[source,java,linenums]
----
package com.makingdevs.practica14;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.util.Assert;

import com.makingdevs.model.User;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations={"SpELInjection.xml"})
public class SpELXmlConfigTests {

  @Autowired
  SystemInfo systemInfo;

  @Autowired
  User userInfoSpel;

  @Autowired
  User userInfoPlaceholders;

  @Test
  public void testSpELInjection() {
    Assert.notNull(systemInfo);
    Assert.notNull(systemInfo.getJavaHome());
    // everything else ...
    System.out.println(systemInfo);
  }

  @Test
  public void testSpELInjectionOnUser(){
    Assert.notNull(userInfoSpel);
    Assert.isTrue(userInfoSpel.getUsername().equals("makingdevs"));
    Assert.isTrue(userInfoSpel.isEnabled());
    Assert.isTrue(userInfoSpel.getId() == 100L);
  }

  @Test
  public void testSpELInjectionPlaceholders(){
    Assert.notNull(userInfoPlaceholders);
    Assert.isTrue(userInfoPlaceholders.getUsername().equals("makingdevs"));
    Assert.isTrue(userInfoPlaceholders.isEnabled());
    Assert.isTrue(userInfoPlaceholders.getId() == 100L);
  }
}
----

### Uso de SpEL en configuración basada en anotaciones

*db_parameters.properties*

----
driver=org.postgresql.Driver
url=jdbc:postgresql://localhost:5432/MakingDevs
user=db_md
password=mejorusatulocal
----

*AnnotationConfigAppCtx.xml*

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:util="http://www.springframework.org/schema/util"
  xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-4.0.xsd">

  <util:properties id="dbProperties" location="classpath:/com/makingdevs/practica15/db_parameters.properties" />
</beans>
----

*DBInfo.java*

[source,java,linenums]
----
package com.makingdevs.practica15;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.ImportResource;
import org.springframework.stereotype.Component;

@Configuration
@ImportResource({"classpath:/com/makingdevs/practica15/AnnotationConfigAppCtx.xml"})
@Component
public class DBInfo {
  @Value("#{dbProperties['username'] ?: 'username'}")
  private String username;
  @Value("#{dbProperties['password'] ?: 'password'}")
  private String password;
  @Value("#{dbProperties['url'] ?: 'jdbc:h2:tcp://localhost/md'}")
  private String url;
  @Value("#{dbProperties['driver'] ?: 'org.h2.Driver'}")
  private String driver;

  public String getUsername() {
    return username;
  }
  public String getPassword() {
    return password;
  }
  public String getUrl() {
    return url;
  }
  public String getDriver() {
    return driver;
  }
}
----

*SpELAnnotatedTests.java*

[source,java,linenums]
----
package com.makingdevs.practica15;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import static org.springframework.util.Assert.*;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(classes = { DBInfo.class })
public class SpELAnnotatedTests {

  @Autowired
  DBInfo dbInfo;

  @Test
  public void testDBProperties() {
    notNull(dbInfo);
    isTrue(dbInfo.getDriver().equals("org.postgresql.Driver"));
    isTrue(dbInfo.getUrl().equals("jdbc:postgresql://localhost:5432/MakingDevs"));
    // Anything else...
  }
}
----

## Spring Profiles

La definición de beans de profile es un mecanismo en el contenedor central de Spring que permite el registro de diferentes beans en diferentes entornos. Esta característica puede ayudarnos en un par de casos de uso:

* Trabajar con una base de datos local contra una base de datos en producción, o bien un DataSource en QA o Producción
* Registrar infraestructura de monitoreo solamente cuando se despliega una aplicación en un entorno de medición de rendimiento
* Registrar implementaciones personalizadas de beans para una aplicación A y una aplicación B
* Registrar infraestructra de brokers, parámetros de SMTP, o cualquier otro elemento externo que sea parte del entorno de la aplicación

*UserServiceDevImpl.java*

[source,java,linenums]
----
package com.makingdevs.practica16;

import com.makingdevs.model.User;
import com.makingdevs.services.UserService;

public class UserServiceDevImpl implements UserService {

  @Override
  public User createUser(String username) {
    System.out.println("Creating user in development environment");
    return null;
  }

  // Another implemented methods...

}
----

*UserServiceProdImpl.java*

[source,java,linenums]
----
package com.makingdevs.practica16;

import com.makingdevs.model.User;
import com.makingdevs.services.UserService;

public class UserServiceProdImpl implements UserService {

  @Override
  public User createUser(String username) {
    System.out.println("Creating user in production environment");
    return null;
  }

  // Another implemented methods...
}
----

*ProfileAppCtx.xml*

[source,xml,linenums]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">

  <beans profile="dev">
    <bean class="com.makingdevs.practica16.UserServiceDevImpl"/>
  </beans>

  <beans profile="prod">
    <bean class="com.makingdevs.practica16.UserServiceProdImpl"/>
  </beans>
</beans>
----

*ProfileTests.java*

[source,java,linenums]
----
package com.makingdevs.practica16;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.util.Assert;

import com.makingdevs.services.UserService;

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations={"ProfileAppCtx.xml"})
@ActiveProfiles(profiles={"dev"}) // Change to 'prod'
public class ProfileTests {

  @Autowired
  UserService userService;

  @Test
  public void testProfileInBean() {
    Assert.notNull(userService);
    userService.createUser("makingdevs");
  }

}
----

[WARNING]
====
Hay algunas coas que debes observar cuando consideras usar perfiles en la definición de los beans:

* No uses perfiles si una aproximación más simple puede resolver el problema
* El conjunto de beans registrado entre dos perfiles deberías ser probablemente más similar que diferente
* Se cuidadoso con no poner mucho en producción
====

Aunque puedes usar la propiedad de sistema `spring.profiles.active` para determinar de forma externalizada que ambiente se usará. Adicionalmente, podemos usar anotaciones para configurar los perfiles.

*StandaloneDataConfig.java*

[source,java,linenums]
----
@Configuration
@Profile("dev")
public class StandaloneDataConfig {

  @Bean
  public DataSource dataSource() {
    return new EmbeddedDatabaseBuilder()
    .setType(EmbeddedDatabaseType.HSQL)
    .addScript("classpath:com/bank/config/sql/schema.sql")
    .addScript("classpath:com/bank/config/sql/test-data.sql")
    .build();
  }
}
----

*JndiDataConfig.java*

[source,java,linenums]
----
@Configuration
@Profile("production")
public class JndiDataConfig {

  @Bean
  public DataSource dataSource() throws Exception {
    Context ctx = new InitialContext();
    return (DataSource) ctx.lookup("java:comp/env/jdbc/datasource");
  }
}
----

TIP: Podrás definir que entorno utilizar incluso en aplicaciones web de forma externalizada para determinar el conjunto de beans que corresponden a una aplicación.


[small]#Powered by link:http://makingdevs.com/[MakingDevs.com]#
